[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

board_build.partitions = huge_app.csv

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_flags =
    -O2
    -D CORE_DEBUG_LEVEL=0

monitor_speed = 115200

lib_deps = 
    madhephaestus/ESP32Servo@^1.1.0
    https://github.com/madhephaestus/ESP32Encoder
    https://github.com/br3ttb/Arduino-PID-Library
    Wire
    ; ps4controller
    https://github.com/rodneybakiskan/ps5-esp32